# This template is heavily inspired by the Graysky.js's template:

name: 🐞 Bug Report
description: Create a bug report to help us improve
title: 'bug: '
labels: ['bug']
body:
    - type: textarea
      attributes:
          label: Describe the bug
          description: A clear and concise description of the bug, as well as what you expected to happen when encountering it.
      validations:
          required: true
    - type: textarea
      attributes:
          label: To reproduce
          description: Describe how to reproduce your bug. Steps, code snippets, reproduction repos etc.
      validations:
          required: true
    - type: input
      attributes:
          label: VSCode version
          description: Please provide the version of VSCode you are using.
      validations:
          required: true
    - type: textarea
      attributes:
          label: Additional information
          description: Add any other information related to the bug here, screenshots if applicable.
